### PR TITLE
Add R0 slider

### LINKED ISSUE #37: R0 in a slider
I think I'd actually like R0 to appear in the input sidebar

One day we might have a little toggle that allows you to either hold R0 fixed and set the infectious rate = R0/infectious period, or hold the rate constant and wiggle R0=rate*period (like we're doing now)

_Originally posted by @swo in https://github.com/CDCgov/cfa-ring-vax-widget/pull/32#discussion_r1890568154_

### PR DESCRIPTION
**Pull request by swo**
- User specifies one of R0 or infection rate to specify
- The other value is shown on a grayed-out slider
- On the backend:
  - The upper and lower limits for infection duration are set (with the duration > 0 as a requirement, to avoid infinite infection rate)
  - R0 has upper and lower limits (lower limit is zero)
  - Limits on infection rate are set by limits on duration and R0
- If infection rate is varied, and it is set so high that R0>10, then a warning displays

Resolves #37

### CODE REVIEW

**Comment by afmagee42** [comment]
> I had to have the order of the two sliders swap. There's probably some way to do this nicer, but this is a start.

Probably something with either [`st.empty()`](https://docs.streamlit.io/knowledge-base/using-streamlit/insert-elements-out-of-order) or [`st.session_state`](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.session_state). But agreed it's not a serious issue.

> Limits on infection rate are set by limits on duration and R0. To get to the maximum value, duration and R0 must both be pulled to their maximum, which maybe is a little weird, but I think it's the only way to make it work.

That is not the experience I'm having running the app. The greyed out bar for infection rate gets a bigger maximum when I set R0 and infection duration to maximum. But then when I toggle to infection rate, it gets set to the default and its range goes to [0,1].

**Comment by afmagee42** [comment]
I think that if you want persistent behavior across changing the R toggle, you might need `session_state`?

**Comment by swo** [comment]
> I think that if you want persistent behavior across changing the R toggle, you might need `session_state`?

Reworked! It took me a while to figure out how to do this, but it was simpler in the end than I expected

The thing I settled on was:

- Give each slider a key
- Set the default values for the sliders by adjusting the session state at the top of the script
- Set the slider values in callbacks using the session state
- Use the output values from the sliders in downstream logic (I *think* it would be equivalent to use the session state value, but this looks cleaner; the callback logic is in session state, and the downstream logic is all in normal variable)

**Comment by afmagee42** [comment]
If I mess with the `infectious_duration` slider at all now I get

> AssertionError:
Traceback:
File "ringvax/app.py", line 359, in <module>
    app()
File "ringvax/app.py", line 155, in app
    assert np.isclose(R0, infection_rate * infectious_duration)

**Comment by afmagee42** [comment]
I have tried adding the R0 callback, alternately the rate callback, to `infectious_duration` and making sure `infectious_duration` had a `session_default` but the error persists.

Print-statement debugging says `R0` isn't being recomputed in either case, so while I can't rule out that those are missing, I think the callbacks are not quite right?

**Review by afmagee42 — CHANGES_REQUESTED** [review]
https://github.com/CDCgov/cfa-ring-vax-widget/pull/50#issuecomment-2560506355

**Comment by swo** [comment]
Good catch. There's still something in here about execution I don't understand, but I came up with a working solution: a single callback for all three sliders.

**Review by afmagee42 — APPROVED** [review]

**Pull request merged**
